server:
  port: 8081
spring:
  application:
    name: pizza-read
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
  zipkin:
    base-url: http://localhost:9411
  logging:
    level:
      org.springframework.cloud.sleuth: DEBUG
      zipkin2: DEBUG
  datasource:
    password: admin123
    url: jdbc:postgresql://localhost:5432/pizza_db
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

