server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: true
      server:
        native:
          searchLocations: classpath:/configuracion
  profiles:
    active: native
  zipkin:
      base-url: http://localhost:9411
